/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.swagger_codegen_maven.api;

import com.example.swagger_codegen_maven.model.Annonce;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Annonce", description = "the Annonce API")
public interface AnnonceApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/v1/annonces : create an annonce
     * create an annonce
     *
     * @param annonce  (optional)
     * @return created successfully (status code 201)
     */
    @Operation(
        operationId = "createAnnonce",
        summary = "create an annonce",
        description = "create an annonce",
        tags = { "Annonce" },
        responses = {
            @ApiResponse(responseCode = "201", description = "created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Annonce.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/annonces",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Annonce> _createAnnonce(
        @Parameter(name = "Annonce", description = "") @Valid @RequestBody(required = false) Annonce annonce
    ) throws Exception {
        return createAnnonce(annonce);
    }

    // Override this method
    default  ResponseEntity<Annonce> createAnnonce(Annonce annonce) throws Exception {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"distance\" : 0.8008281904610115, \"prix\" : 6.027456183070403, \"titre\" : \"\", \"author\" : { \"image\" : \"image\", \"createdAt\" : \"createdAt\", \"firstname\" : \"firstname\", \"password\" : \"password\", \"deletedAt\" : \"deletedAt\", \"role\" : \"role\", \"deleted\" : true, \"phone\" : \"phone\", \"id\" : \"id\", \"emailValidated\" : true, \"username\" : \"username\", \"lastname\" : \"lastname\" }, \"offres\" : 1.4658129805029452, \"destination\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"photos\" : [ \"photos\", \"photos\" ], \"createdAt\" : \"\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"id\" : \"id\", \"departure\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"open\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/v1/annonce/{id}
     *
     * @param id  (required)
     * @param byAdmin  (optional)
     * @return deleted successfully (status code 200)
     *         or error when deleting annonce (status code 400)
     */
    @Operation(
        operationId = "deleteAnnonce",
        tags = { "Annonce" },
        responses = {
            @ApiResponse(responseCode = "200", description = "deleted successfully"),
            @ApiResponse(responseCode = "400", description = "error when deleting annonce")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/v1/annonce/{id}"
    )
    default ResponseEntity<Void> _deleteAnnonce(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "byAdmin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "byAdmin", required = false) String byAdmin
    ) throws Exception {
        return deleteAnnonce(id, byAdmin);
    }

    // Override this method
    default  ResponseEntity<Void> deleteAnnonce(String id, String byAdmin) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/annonce/{id}
     *
     * @param id  (required)
     * @param byAdmin  (optional)
     * @return get successfully (status code 200)
     *         or error when fetching annonce (status code 400)
     */
    @Operation(
        operationId = "getAnnonceById",
        tags = { "Annonce" },
        responses = {
            @ApiResponse(responseCode = "200", description = "get successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Annonce.class))
            }),
            @ApiResponse(responseCode = "400", description = "error when fetching annonce")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/annonce/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Annonce> _getAnnonceById(
        @Pattern(regexp = "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$") @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "byAdmin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "byAdmin", required = false) String byAdmin
    ) throws Exception {
        return getAnnonceById(id, byAdmin);
    }

    // Override this method
    default  ResponseEntity<Annonce> getAnnonceById(String id, String byAdmin) throws Exception {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"distance\" : 0.8008281904610115, \"prix\" : 6.027456183070403, \"titre\" : \"\", \"author\" : { \"image\" : \"image\", \"createdAt\" : \"createdAt\", \"firstname\" : \"firstname\", \"password\" : \"password\", \"deletedAt\" : \"deletedAt\", \"role\" : \"role\", \"deleted\" : true, \"phone\" : \"phone\", \"id\" : \"id\", \"emailValidated\" : true, \"username\" : \"username\", \"lastname\" : \"lastname\" }, \"offres\" : 1.4658129805029452, \"destination\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"photos\" : [ \"photos\", \"photos\" ], \"createdAt\" : \"\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"id\" : \"id\", \"departure\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"open\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/annonces
     *
     * @param cityDepart  (optional, default to )
     * @param cityArrivee  (optional, default to )
     * @param userId  (optional, default to )
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @param byAdmin  (optional)
     * @return get successfully (status code 200)
     */
    @Operation(
        operationId = "getLatestAnnonce",
        tags = { "Annonce" },
        responses = {
            @ApiResponse(responseCode = "200", description = "get successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/annonces",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> _getLatestAnnonce(
        @Parameter(name = "city_depart", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "city_depart", required = false, defaultValue = "") String cityDepart,
        @Parameter(name = "city_arrivee", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "city_arrivee", required = false, defaultValue = "") String cityArrivee,
        @Parameter(name = "user_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "user_id", required = false, defaultValue = "") String userId,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size,
        @Parameter(name = "byAdmin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "byAdmin", required = false) String byAdmin
    ) throws Exception {
        return getLatestAnnonce(cityDepart, cityArrivee, userId, page, size, byAdmin);
    }

    // Override this method
    default  ResponseEntity<Object> getLatestAnnonce(String cityDepart, String cityArrivee, String userId, Integer page, Integer size, String byAdmin) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/v1/annonce/{id}
     *
     * @param id  (required)
     * @param byAdmin  (optional)
     * @param annonce  (optional)
     * @return updated successfully (status code 200)
     *         or error when updating annonce (status code 400)
     */
    @Operation(
        operationId = "updateAnnonce",
        tags = { "Annonce" },
        responses = {
            @ApiResponse(responseCode = "200", description = "updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Annonce.class))
            }),
            @ApiResponse(responseCode = "400", description = "error when updating annonce")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/v1/annonce/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Annonce> _updateAnnonce(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "byAdmin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "byAdmin", required = false) String byAdmin,
        @Parameter(name = "Annonce", description = "") @Valid @RequestBody(required = false) Annonce annonce
    ) throws Exception {
        return updateAnnonce(id, byAdmin, annonce);
    }

    // Override this method
    default  ResponseEntity<Annonce> updateAnnonce(String id, String byAdmin, Annonce annonce) throws Exception {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"distance\" : 0.8008281904610115, \"prix\" : 6.027456183070403, \"titre\" : \"\", \"author\" : { \"image\" : \"image\", \"createdAt\" : \"createdAt\", \"firstname\" : \"firstname\", \"password\" : \"password\", \"deletedAt\" : \"deletedAt\", \"role\" : \"role\", \"deleted\" : true, \"phone\" : \"phone\", \"id\" : \"id\", \"emailValidated\" : true, \"username\" : \"username\", \"lastname\" : \"lastname\" }, \"offres\" : 1.4658129805029452, \"destination\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"photos\" : [ \"photos\", \"photos\" ], \"createdAt\" : \"\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"id\" : \"id\", \"departure\" : { \"zipCode\" : \"zipCode\", \"deletedAt\" : \"deletedAt\", \"deleted\" : true, \"city\" : \"city\", \"libelle\" : \"libelle\" }, \"open\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
